### ISSUE TITLE
Hash mismatch between header body hash

### ISSUE THREAD

**Issue by soywod** [HIP-Labs/HIP-Subnet#9]
I get this error after updating and restarting my miner, when receiving a task:

```text
1|miner  | 2024-06-14 07:43:23.765 |      TRACE       | Run exception: Hash mismatch between header body hash 5bef193673f8d9161fdffe4be4850b73388db33b87c0a1dc0b751a6e55da1f50 and parsed body hash 929d404a973fe4e432010455a237ff4cc7ac32064f5f9ca36e3beafd2f0c29c9
1|miner  | 2024-06-14 07:43:23.769 |      TRACE       | Forward exception: Traceback (most recent call last):
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 105, in receive
1|miner  |     return self.receive_nowait()
1|miner  |            ^^^^^^^^^^^^^^^^^^^^^
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
1|miner  |     raise WouldBlock
1|miner  | anyio.WouldBlock
1|miner  | During handling of the above exception, another exception occurred:
1|miner  | Traceback (most recent call last):
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
1|miner  |     return receiver.item
1|miner  |            ^^^^^^^^^^^^^
1|miner  | AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'
1|miner  | During handling of the above exception, another exception occurred:
1|miner  | Traceback (most recent call last):
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
1|miner  |     message = await recv_stream.receive()
1|miner  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 120, in receive
1|miner  |     raise EndOfStream
1|miner  | anyio.EndOfStream
1|miner  | During handling of the above exception, another exception occurred:
1|miner  | Traceback (most recent call last):
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/bittensor/axon.py", line 1408, in run
1|miner  |     response = await call_next(request)
1|miner  |                ^^^^^^^^^^^^^^^^^^^^^^^^
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
1|miner  |     raise app_exc
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
1|miner  |     await self.app(scope, receive_or_disconnect, send_no_error)
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
1|miner  |     raise exc
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
1|miner  |     await self.app(scope, receive, sender)
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
1|miner  |     raise e
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
1|miner  |     await self.app(scope, receive, send)
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
1|miner  |     await route.handle(scope, receive, send)
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
1|miner  |     await self.app(scope, receive, send)
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
1|miner  |     response = await func(request)
1|miner  |                ^^^^^^^^^^^^^^^^^^^
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/fastapi/routing.py", line 231, in app
1|miner  |     solved_result = await solve_dependencies(
1|miner  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
1|miner  |     solved = await call(**sub_values)
1|miner  |              ^^^^^^^^^^^^^^^^^^^^^^^^
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/bittensor/axon.py", line 712, in verify_body_integrity
1|miner  |     raise ValueError(
1|miner  | ValueError: Hash mismatch between header body hash 5bef193673f8d9161fdffe4be4850b73388db33b87c0a1dc0b751a6e55da1f50 and parsed body hash 929d404a973fe4e432010455a237ff4cc7ac32064f5f9ca36e3beafd2f0c29c9
1|miner  | During handling of the above exception, another exception occurred:
1|miner  | Traceback (most recent call last):
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/bittensor/axon.py", line 1068, in dispatch
1|miner  |     response = await self.run(synapse, call_next, request)
1|miner  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1|miner  |   File "/home/debian/sn36/venv/lib/python3.11/site-packages/bittensor/axon.py", line 1422, in run
1|miner  |     raise RunException(f"Internal server error with error: {str(e)}")
1|miner  | bittensor.errors.RunException: Internal server error with error: Hash mismatch between header body hash 5bef193673f8d9161fdffe4be4850b73388db33b87c0a1dc0b751a6e55da1f50 and parsed body hash 929d404a973fe4e432010455a237ff4cc7ac32064f5f9ca36e3beafd2f0c29c9
1|miner  | TRACE:    185.150.27.254:12146 - ASGI [2] Send {'type': 'http.response.start', 'status': 500, 'headers': '<...>'}
1|miner  | INFO:     185.150.27.254:12146 - "POST /TaskSynapse HTTP/1.1" 500 Internal Server Error
1|miner  | 2024-06-14 07:43:23.769 |      ERROR       | RunException: Internal server error with error: Hash mismatch between header body hash 5bef193673f8d9161fdffe4be4850b73388db33b87c0a1dc0b751a6e55da1f50 and parsed body hash 929d404a973fe4e432010455a237ff4cc7ac32064f5f9ca36e3beafd2f0c29c9
1|miner  | TRACE:    185.150.27.254:12146 - ASGI [2] Send {'type': 'http.response.body', 'body': '<237 bytes>'}
1|miner  | 2024-06-14 07:43:23.789 |      TRACE       | axon     | --> | 237 B | TaskSynapse | 5CaeumxZb7VBheeNhWHrgxXNrwaoG91h9azykQDqnBWvnW7r | 185.150.27.254:12146  | 500 | Internal server error with error: Hash mismatch between header body hash 5bef193673f8d9161fdffe4be4850b73388db33b87c0a1dc0b751a6e55da1f50 and parsed body hash 929d404a973fe4e432010455a237ff4cc7ac32064f5f9ca36e3beafd2f0c29c9
```

Python 3.11, bittensor cli v6.9.3, commit hash `ee31a922588a2e4d4ed1c620c5813be515ab1197` (`v1.3.0`).

**Comment by tarabukinivan** [comment]
after updating
```
32|miner  | TRACE:    89.187.159.44:51618 - HTTP connection made
32|miner  | TRACE:    89.187.159.44:51618 - ASGI [6] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('167.235.39.5', 8091), 'client': ('89.187.159.44', 51618), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/TaskSynapse', 'raw_path': b'/TaskSynapse', 'query_string': b'', 'headers': '<...>', 'state': {}}
32|miner  | 2024-06-14 08:40:45.376 |      TRACE       | axon     | <-- | 12786 B | TaskSynapse | 5CXRfP2ekFhe62r7q3vppRajJmGhTi7vwvb2yr79jveZ282w | 89.187.159.44:51618 | 200 | Success
32|miner  | 2024-06-14 08:40:45.381 |      TRACE       | Not Blacklisting recognized hotkey 5CXRfP2ekFhe62r7q3vppRajJmGhTi7vwvb2yr79jveZ282w
32|miner  | 2024-06-14 08:40:45.387 |      TRACE       | Prioritizing 5CXRfP2ekFhe62r7q3vppRajJmGhTi7vwvb2yr79jveZ282w with value: 98344.3515625
32|miner  | TRACE:    89.187.159.44:51618 - ASGI [6] Receive {'type': 'http.request', 'body': '<12786 bytes>', 'more_body': False}
32|miner  | 2024-06-14 08:40:45.415 |      TRACE       | Run exception: Hash mismatch between header body hash e26d416cdb9b4179251fa9979564fdc7bfaa0e5f300923c9a94cb04f27521d88 and parsed body hash 4c06b0c2b50efbd6dbe4134f96ff3a53a80cd5b5ff82a0968aba5213e98eccc3
32|miner  | TRACE:    89.187.159.44:51618 - ASGI [6] Send {'type': 'http.response.start', 'status': 500, 'headers': '<...>'}
32|miner  | INFO:     89.187.159.44:51618 - "POST /TaskSynapse HTTP/1.1" 500 Internal Server Error
32|miner  | TRACE:    89.187.159.44:51618 - ASGI [6] Send {'type': 'http.response.body', 'body': '<237 bytes>'}
32|miner  | 2024-06-14 08:40:45.470 |      TRACE       | Forward exception: Traceback (most recent call last):
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 105, in receive
32|miner  |     return self.receive_nowait()
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
32|miner  |     raise WouldBlock
32|miner  | anyio.WouldBlock
32|miner  | During handling of the above exception, another exception occurred:
32|miner  | Traceback (most recent call last):
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
32|miner  |     return receiver.item
32|miner  | AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'
32|miner  | During handling of the above exception, another exception occurred:
32|miner  | Traceback (most recent call last):
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
32|miner  |     message = await recv_stream.receive()
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 120, in receive
32|miner  |     raise EndOfStream
32|miner  | anyio.EndOfStream
32|miner  | During handling of the above exception, another exception occurred:
32|miner  | Traceback (most recent call last):
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/bittensor/axon.py", line 1408, in run
32|miner  |     response = await call_next(request)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
32|miner  |     raise app_exc
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
32|miner  |     await self.app(scope, receive_or_disconnect, send_no_error)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
32|miner  |     raise exc
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
32|miner  |     await self.app(scope, receive, sender)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
32|miner  |     raise e
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
32|miner  |     await self.app(scope, receive, send)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
32|miner  |     await route.handle(scope, receive, send)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
32|miner  |     await self.app(scope, receive, send)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
32|miner  |     response = await func(request)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
32|miner  |     solved_result = await solve_dependencies(
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
32|miner  |     solved = await call(**sub_values)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/bittensor/axon.py", line 712, in verify_body_integrity
32|miner  |     raise ValueError(
32|miner  | ValueError: Hash mismatch between header body hash e26d416cdb9b4179251fa9979564fdc7bfaa0e5f300923c9a94cb04f27521d88 and parsed body hash 4c06b0c2b50efbd6dbe4134f96ff3a53a80cd5b5ff82a0968aba5213e98eccc3
32|miner  | During handling of the above exception, another exception occurred:
32|miner  | Traceback (most recent call last):
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/bittensor/axon.py", line 1068, in dispatch
32|miner  |     response = await self.run(synapse, call_next, request)
32|miner  |   File "/root/HIP-Subnet/venv/lib/python3.10/site-packages/bittensor/axon.py", line 1422, in run
32|miner  |     raise RunException(f"Internal server error with error: {str(e)}")
32|miner  | bittensor.errors.RunException: Internal server error with error: Hash mismatch between header body hash e26d416cdb9b4179251fa9979564fdc7bfaa0e5f300923c9a94cb04f27521d88 and parsed body hash 4c06b0c2b50efbd6dbe4134f96ff3a53a80cd5b5ff82a0968aba5213e98eccc3
32|miner  | 2024-06-14 08:40:45.476 |      ERROR       | RunException: Internal server error with error: Hash mismatch between header body hash e26d416cdb9b4179251fa9979564fdc7bfaa0e5f300923c9a94cb04f27521d88 and parsed body hash 4c06b0c2b50efbd6dbe4134f96ff3a53a80cd5b5ff82a0968aba5213e98eccc3
32|miner  | 2024-06-14 08:40:45.499 |      TRACE       | axon     | --> | 237 B | TaskSynapse | 5CXRfP2ekFhe62r7q3vppRajJmGhTi7vwvb2yr79jveZ282w | 89.187.159.44:51618  | 500 | Internal server error with error: Hash mismatch between header body hash e26d416cdb9b4179251fa9979564fdc7bfaa0e5f300923c9a94cb04f27521d88 and parsed body hash 4c06b0c2b50efbd6dbe4134f96ff3a53a80cd5b5ff82a0968aba5213e98eccc3
32|miner  | TRACE:    89.187.159.44:51618 - ASGI [6] Completed
32|miner  | 2024-06-14 08:40:46.562 |       INFO       | Miner running... 1718354446.562109
32|miner  | 2024-06-14 08:40:48.008 |       INFO       | resync_metagraph()
32|miner  | TRACE:    89.187.159.44:51618 - HTTP connection lost
32|miner  | 2024-06-14 08:40:51.160 |       INFO       | resync_metagraph()
32|miner  | 2024-06-14 08:40:51.571 |       INFO       | Miner running... 1718354451.5714383
32|miner  | 2024-06-14 08:40:54.211 |       INFO       | resync_metagraph()
32|miner  | 2024-06-14 08:40:56.586 |       INFO       | Miner running... 1718354456.5865726
32|miner  | 2024-06-14 08:40:57.052 |       INFO       | resync_metagraph()
32|miner  | 2024-06-14 08:40:59.476 |       INFO       | resync_metagraph()
32|miner  | 2024-06-14 08:41:01.619 |       INFO       | Miner running... 1718354461.6195848
32|miner  | 2024-06-14 08:41:02.521 |       INFO       | resync_metagraph()
32|miner  | 2024-06-14 08:41:05.566 |       INFO       | resync_metagraph()
32|miner  | 2024-06-14 08:41:06.826 |       INFO       | Miner running... 1718354466.8260832
32|miner  | 2024-06-14 08:41:08.463 |       INFO       | resync_metagraph()
```

**Comment by hamzatrq** [comment]
@tarabukinivan @soywod thats not an error. Its just telling you that with the update the protocol/synapse changed so now there a difference between the request that the miner received from the validator vs what it was expecting to receive.

It just means that the validator sending the task hasnt updated to the latest version
